import logging as log
import os
from abc import ABC, abstractmethod
from collections.abc import Callable
from typing import Any

import numpy as np
from cothread import Sleep, cothread
from cothread.catools import caput
from pytac.element import EpicsElement

from dls_bba.components import Components
from dls_bba.datatypes import (
    BPMOffset,
    FullResults,
    OscillationPlane,
    QuadResults,
    RawData,
)
from dls_bba.machine import ORIGIN_SUFFIXES, Machine
from dls_bba.plotting import bba_offsets_plot


class Algorithm(ABC):
    """Abstract base class for all BBA algorithms."""

    def __init__(self, machine: Machine) -> None:
        """Constructor for Algorithm class.

        Args:
            machine: The machine object.
        """
        self._machine = machine
        self._pause_event = cothread.Event()
        self._stop_event = cothread.Event()

    @abstractmethod
    def run(self, component_pair: list[Components]) -> RawData | None:
        """Runs the algorithm.

        Args:
            component_pair: The component pair to run the algorithm on.

        Returns:
            The RawData object generated by the algorithm.
        """
        pass

    @abstractmethod
    def analyse(self, rawdata: RawData) -> FullResults:
        """Analyses the raw data.

        Args:
            rawdata: The raw data to analyse.

        Returns:
            The FullResults object generated by the analysis.
        """
        pass

    def pause_run(self) -> None:
        self._pause_event.Signal("pause")

    def resume_run(self) -> None:
        self._pause_event.Signal("resume")

    def stop_run(self) -> None:
        self._stop_event.Signal()

    def _check_and_wait_pause_status(self) -> None:
        """Check if the pause event has been triggered.

        If it has not been triggered, then immediately return. If it has been triggered,
        then wait until it is triggered again but with the 'resume' state string.
        """
        if self._pause_event:
            log.info("Algorithm paused")
            state = self._pause_event.Wait()
            while state != "resume":
                state = self._pause_event.Wait()
                log.info("Algorithm resumed")

    def _check_stop_status(self) -> bool:
        """Check if the stop event has been triggered.

        Returns:
            True if the event is set, false if not.
        """
        return bool(self._stop_event)

    def calculate_quad_setpoints(
        self, quadrupole: EpicsElement
    ) -> tuple[float, float, float, float, float]:
        """Calculates the quadrupole setpoints.

        Args:
            quadrupole: The quadrupole to calculate the setpoints for.

        Returns:
            A tuple containing the four quadrupole setpoints and step size.
        """
        quad_step_percent = self._machine.config["QUADRUPOLE_STEP_PERCENT"] * 1e-2

        quad_setpoint = self._machine.get_quad_setpoint(quadrupole)
        quad_step = quad_setpoint * quad_step_percent
        quad_start_high = quad_setpoint + (2 * quad_step)
        quad_high = quad_setpoint + quad_step
        quad_low = quad_setpoint - quad_step
        return quad_start_high, quad_high, quad_low, quad_setpoint, quad_step

    def create_offsets_dict(
        self,
        results: dict[str, OscillationPlane[QuadResults]],
        metadata: dict[str, Any],
    ) -> dict[str, OscillationPlane[BPMOffset]]:
        """Creates a dictionary containing the old and new offsets.

        Args:
            results: The results of the analysis.
            metadata: The metadata of the BBA run.

        Returns:
            A dictionary containing the old, new and difference in offsets for each BPM.
        """
        offsets: dict[str, OscillationPlane[BPMOffset]] = {}
        bpm_name = metadata["bpm_name"]
        bpm_index = metadata["bpm_index"]

        for index, axis in enumerate(["x", "y"]):
            # Get current BBA offset.
            old_bba = float(self._machine.get_bba_offsets()[index][bpm_index])
            # Calculate the change needed.
            difference = self.calculate_new_offsets(results, axis)
            # Calculate the new BBA offset.
            new_bba = round(old_bba + difference[0], 4)
            # Set all values to 4d.p.
            diff_value, diff_error = [round(v, 4) for v in difference]

            if bpm_name not in offsets.keys():
                offsets[bpm_name] = OscillationPlane()
            offsets[bpm_name][axis] = BPMOffset(
                old_bba, new_bba, diff_value, diff_error
            )

        return offsets

    def calculate_new_offsets(
        self, results: dict[str, OscillationPlane[QuadResults]], axis: str
    ) -> list[float]:
        """Calculates the new offsets for a given axis.

        Args:
            results: The results of the analysis.
            axis: The axis to calculate the new offsets for.

        Returns:
            A list containing the new offset and the error.
        """
        values = []
        errors = []
        sum_error = 0.0
        for key in results.keys():
            values.append(results[key][axis.lower()].mean_offset)
            errors.append(results[key][axis.lower()].std_dev_offset)
            sum_error += (errors[-1] / values[-1]) ** 2
        mean_value = float(np.mean(values))
        total_error = np.sqrt(sum_error) * mean_value
        return [mean_value, total_error]

    def reformat_and_save_offsets(
        self,
        results_list: list[FullResults],
        save_location: str,
    ):
        offsets_dict: dict[str, OscillationPlane[BPMOffset]] = {}
        for results in results_list:
            offsets_dict.update(results.bpm_offsets.items())

        self._save_bba_offsets(offsets_dict, save_location)
        return offsets_dict

    def use_bba_offsets(
        self,
        results_list: list[FullResults],
        save_location: str,
        question_callback: Callable[[str], bool],
    ) -> None:
        """Saves, plots and asks the user if they want to apply the BBA offsets.

        Args:
            results_list: The list of results to use.
            save_location: The location to save the results to.
            question_callback: The question function for the console or gui.
        """
        offsets_dict = self.reformat_and_save_offsets(results_list, save_location)
        bba_offsets_plot(self._machine, offsets_dict, save_location)
        if question_callback("Apply these BBA offsets? (y / n) :"):
            self.apply_bba_offsets(offsets_dict)
            self._machine.apply_feedbacks()

    def _save_bba_offsets(
        self,
        offsets_dict: dict[str, OscillationPlane[BPMOffset]],
        save_location: str,
    ) -> None:
        """Saves the BBA offsets to a file in a human readable format.

        Args:
            offsets_dict: The dictionary containing the PV and the offsets to apply.
            save_location: The location to save the results to.
        """
        filename = os.path.join(save_location, "results.txt")
        with open(filename, "w") as writer:
            for key, value in offsets_dict.items():
                for plane in ["x", "y"]:
                    pv_name = key + ORIGIN_SUFFIXES["BBA"].format(axis=plane.upper())
                    line = (
                        f"{pv_name} Absolute change: {value[plane].diff_value} "
                        f"+/- {value[plane].diff_error} [mm]"
                    )
                    log.info(line)
                    writer.write(line + "\n")
                    line = (
                        f"{pv_name} Old: {value[plane].old_value} [mm], "
                        f"New: {value[plane].new_value} [mm]"
                    )
                    log.info(line)
                    writer.write(line + "\n")
            writer.close()

    def apply_bba_offsets(
        self,
        offsets_dict: dict[str, OscillationPlane[BPMOffset]],
    ) -> None:
        """Applies the BBA offsets to the machine.

        Args:
            offsets_dict: The dictionary containing the PV and the offsets to apply.
        """
        pv_names = []
        pv_values = []
        for key, value in offsets_dict.items():
            for plane in ["x", "y"]:
                pv_names.append(key + ORIGIN_SUFFIXES["BBA"].format(axis=plane.upper()))
                pv_values.append(value[plane].new_value)
        caput(pv_names, pv_values, wait=True)
        log.info(f"{len(pv_names)} BBA Offsets Applied.")
        Sleep(0.2)
