import logging as log
import os
from abc import ABC, abstractmethod
from typing import Any, Callable, Dict, List, Tuple

import numpy as np
from cothread import Sleep
from cothread.catools import caput
from pytac.element import EpicsElement

from dls_bba.components import Components
from dls_bba.datatypes import CalculatedOffset, RawData, Results
from dls_bba.machine import ORIGIN_SUFFIXES, Machine
from dls_bba.plotting import bba_offsets_plot


class Algorithm(ABC):
    """Abstract base class for all BBA algorithms."""

    def __init__(self, machine: Machine) -> None:
        """Constructor for Algorithm class.

        Args:
            machine: The machine object.
        """
        self._machine = machine

    @abstractmethod
    def run(self, component_pair: List[Components]) -> RawData:
        """Runs the algorithm.

        Args:
            component_pair: The component pair to run the algorithm on.

        Returns:
            The RawData object generated by the algorithm.
        """
        pass

    @abstractmethod
    def analyse(self, rawdata: RawData) -> Results:
        """Analyses the raw data.

        Args:
            rawdata: The raw data to analyse.

        Returns:
            The Results object generated by the analysis.
        """
        pass

    def calculate_quad_setpoints(
        self, quadrupole: EpicsElement
    ) -> Tuple[float, float, float, float, float]:
        """Calculates the quadrupole setpoints.

        Args:
            quadrupole: The quadrupole to calculate the setpoints for.

        Returns:
            A tuple containing the four quadrupole setpoints and step size.
        """
        quad_step_percent = self._machine.config["QUADRUPOLE_STEP_PERCENT"] * 1e-2

        quad_setpoint = self._machine.get_quad_setpoint(quadrupole)
        quad_step = quad_setpoint * quad_step_percent
        quad_start_high = quad_setpoint + (2 * quad_step)
        quad_high = quad_setpoint + quad_step
        quad_low = quad_setpoint - quad_step
        return quad_start_high, quad_high, quad_low, quad_setpoint, quad_step

    def create_offsets_dict(
        self, results: Dict[str, List[float]], metadata: Dict[str, Any]
    ) -> Dict[str, CalculatedOffset]:
        """Creates a dictionary containing the old and new offsets.

        Args:
            results: The results of the analysis.
            metadata: The metadata of the BBA run.

        Returns:
            A dictionary containing the old, new and difference in offsets for each BPM.
        """
        offsets: Dict[str, CalculatedOffset] = {}
        bpm_name = metadata["bpm_name"]
        bpm_index = metadata["bpm_index"]

        for index, axis in enumerate(["x", "y"]):
            bpm_key = str(bpm_name + ORIGIN_SUFFIXES["BBA"].format(axis=axis.upper()))
            # Get current BBA offset.
            old_bba = float(self._machine.get_bba_offsets()[index][bpm_index])
            # Calculate the change needed.
            difference = self.calculate_new_offsets(results, axis)
            # Calculate the new BBA offset.
            new_bba = float("%0.4f" % (old_bba + difference[0]))
            # Set all values to 4d.p.
            diff_value, diff_error = [float("%0.4f" % v) for v in difference]

            offsets[bpm_key] = CalculatedOffset(
                old_bba, new_bba, diff_value, diff_error
            )

        return offsets

    def calculate_new_offsets(
        self, results: Dict[str, List[float]], axis: str
    ) -> List[float]:
        """Calculates the new offsets for a given axis.

        Args:
            results: The results of the analysis.
            axis: The axis to calculate the new offsets for.

        Returns:
            A list containing the new offset and the error.
        """
        keys = [key for key in results.keys() if axis in key]
        values = []
        errors = []
        for key in keys:
            values.append(results[key][0])
            errors.append(results[key][1])

        sum_error = 0.0
        mean_value = float(np.mean(values))
        for value, error in zip(values, errors):
            sum_error += (error / value) ** 2
        total_error = np.sqrt(sum_error) * mean_value
        return [mean_value, total_error]

    def reformat_and_save_offsets(
        self,
        results_list: List[Results],
        save_location: str,
    ):
        offsets_dict: Dict[str, CalculatedOffset] = {}
        for results in results_list:
            offsets_dict.update(results.offsets.items())

        self._save_bba_offsets(offsets_dict, save_location)
        return offsets_dict

    def use_bba_offsets(
        self,
        results_list: List[Results],
        save_location: str,
        question: Callable[[str], bool],
    ) -> None:
        """Saves, plots and asks the user if they want to apply the BBA offsets.

        Args:
            results_list: The list of results to use.
            save_location: The location to save the results to.
            question: The question function for the console or gui.
        """
        offsets_dict = self.reformat_and_save_offsets(results_list, save_location)
        bba_offsets_plot(self._machine, offsets_dict, save_location)
        if question("Apply these BBA offsets? (y / n) :"):
            self.apply_bba_offsets(offsets_dict)
            self._machine.apply_feedbacks()

    def _save_bba_offsets(
        self,
        offsets_dict: Dict[str, CalculatedOffset],
        save_location: str,
    ) -> None:
        """Saves the BBA offsets to a file in a human readable format.

        Args:
            offsets_dict: The dictionary containing the PV and the offsets to apply.
            save_location: The location to save the results to.
        """
        filename = os.path.join(save_location, "results.txt")
        with open(filename, "w") as writer:
            for key, value in offsets_dict.items():
                line = f"{key} Absolute change: {value.diff_value} +/- {value.diff_error} [mm]"
                log.info(line)
                writer.write(line)
                line = f"{key} Old: {value.old_value} [mm], New: {value.new_value} [mm]\n"
                log.info(line)
                writer.write(line)
            writer.close()

    def apply_bba_offsets(
        self,
        offsets_dict: Dict[str, CalculatedOffset],
    ) -> None:
        """Applies the BBA offsets to the machine.

        Args:
            offsets_dict: The dictionary containing the PV and the offsets to apply.
        """
        pv_names = []
        pv_values = []
        for key, value in offsets_dict.items():
            pv_names.append(key)
            pv_values.append(value.new_value)
        caput(pv_names, pv_values, wait=True)
        log.info(f"{len(pv_names)} BBA Offsets Applied.")
        Sleep(0.2)
