HORIZONTAL_PLANE = 0  # Fundamental definition of plane orientation
VERTICAL_PLANE = 1
X = HORIZONTAL_PLANE
Y = VERTICAL_PLANE
AXIS_NAMES = {HORIZONTAL_PLANE: "X", VERTICAL_PLANE: "Y"}
CORRECTOR_FAMILIES = {HORIZONTAL_PLANE: "HSTR", VERTICAL_PLANE: "VSTR"}
